### ISSUE TITLE
[Feature]: Change package name

### ISSUE THREAD

**Issue by jaredkotoff** [KitsunedFox/termux-monet#138]
### Feature description

Because this uses the same package name as the official Termux app, Google Play thinks this app is the same as the official one and will try to update it. 
This is really annoying as it fails and will always sit there, blocking the ability to check for other app updates. 
Please change the package name so it does not conflict with the official termux app.

### Additional information

Currently, there is a new update on the Google Play causing this issue and it will not go away until this package is updated to the same version OR the package name is changed (which will prevent this issue in the future)
https://github.com/termux/termux-app/discussions/4000

**Comment by anedroid** [comment]
Well, changing the package name will be difficult, as all the Termux packages expect prefix at /data/data/com.termux/files/usr. That's why you can't use Termux on work profile. By the way, it's a good moment to make it location-agnostic.

Dnia 13 czerwca 2024 07:42:26 CEST, Jared Kotoff ***@***.***> napisał/a:

**Comment by jaredkotoff** [comment]
Ah, what an unfortunate set of circumstances
